CREATE TABLE ITEM(
	ITEM_ID serial PRIMARY KEY,
	ITEM_NAME char(20) NOT NULL
);

CREATE TABLE ITEM_DESCRITION(
	ITEM_ID integer REFERENCES ITEM,
	CREATION_DATE date NOT NULL,
	DESCRIPTION text
);

CREATE TABLE PERSON(
	PERSON_ID serial PRIMARY KEY,
	PERSON_NAME char(25) NOT NULL,
	PERSON_AGE smallint NOT NULL
						CHECK(PERSON_AGE > 0),
	PROFESSION_NAME char(50) NOT NULL,
	ITEM_ID integer UNIQUE REFERENCES ITEM ON DELETE SET NULL
);
CREATE TABLE OWN(
	PERSON_ID integer REFERENCES PERSON,
	ITEM_ID integer REFERENCES ITEM UNIQUE,
	TIME timestamp
);	

CREATE TABLE BODY_PART(
	BODY_PART_ID serial PRIMARY KEY,
	PART_NAME char(25) NOT NULL,
	PERSON_ID integer REFERENCES PERSON
);

CREATE TABLE BODY_PART_ACTION(
	BODY_PART_ID integer REFERENCES BODY_PART UNIQUE,
	ACTION_NAME text NOT NULL,
	ACTION_TIME timestamp
);

CREATE TABLE FLASHLIGHT(
	FLASHLIGHT_ID serial PRIMARY KEY,
	LAMP_TYPE char(20)
);

CREATE TABLE SHIP(
	SHIP_ID serial PRIMARY KEY,
	SHIP_NAME char(50),
	SHIP_TYPE char(25)
);

CREATE TABLE LOCATION(
	SHIP_ID integer REFERENCES SHIP,
	FLASHLIGHT_ID integer REFERENCES FLASHLIGHT UNIQUE
);

CREATE TABLE PORT(
	PORT_ID serial PRIMARY KEY,
	PORT_NAME char(25) NOT NULL,
	CITY_NAME char(25) NOT NULL
);

CREATE TABLE VISITOR_LIST(
	PERSON_ID integer REFERENCES PERSON,
	PORT_ID integer REFERENCES PORT,
	TIME timestamp
);

CREATE TABLE SHIP_IN_PORT(
	SHIP_ID integer REFERENCES SHIP,
	PORT_ID integer REFERENCES PORT,
	TIME timestamp
);

CREATE TABLE WACHED_SHIP (
	PERSON_ID integer REFERENCES PERSON ON DELETE CASCADE,
	SHIP_ID integer REFERENCES SHIP ON DELETE CASCADE,
	PRIMARY KEY (PERSON_ID, SHIP_ID)
);

CREATE TABLE TIME(
	TIME_NAME char(25) PRIMARY KEY,
	START_TIME time,
	END_TIME time,
	UNIQUE(START_TIME, END_TIME)
);

CREATE TABLE LIGHTS_ON_TIME (
	FLASHLIGHT_ID integer REFERENCES FLASHLIGHT ON DELETE CASCADE,
	TIME_NAME char(25) REFERENCES TIME ON DELETE CASCADE,
	PRIMARY KEY (FLASHLIGHT_ID, TIME_NAME)
);

INSERT INTO ITEM (ITEM_NAME)
VALUES
	('binoculars'),
	('book'),
	('gun'),
	('map');
INSERT INTO ITEM_DESCRITION(ITEM_ID, CREATION_DATE, DESCRIPTION)
VALUES
	(1, '2016-11-23', 'item for super vision'),
	(2, '2015-10-23', 'book with pictures');

INSERT INTO PERSON(PERSON_NAME, PERSON_AGE, PROFESSION_NAME)
VALUES
	('Artem', 18, 'student'),
	('Grant', 43, 'archaeologist');

INSERT INTO OWN(PERSON_ID, ITEM_ID, TIME)
VALUES
	(2, 1, '2023-03-02 18:13:44+01'),
	(2, 3, '2022-03-02 12:13:44+01'),
	(2, 4, '2021-03-02 13:13:44+01'),
	(1, 2, '2020-03-02 10:13:44+01');

INSERT INTO BODY_PART(PART_NAME, PERSON_ID)
VALUES
	('hand', 1),
	('head', 1),
	('leg', 2),
	('elbow', 2);

INSERT INTO BODY_PART_ACTION(BODY_PART_ID, ACTION_NAME, ACTION_TIME)
VALUES
	(3, 'push out', '2023-03-02 11:13:44+01'),
	(2, 'tap', '2023-03-01 12:04:54+01');

INSERT INTO FLASHLIGHT(LAMP_TYPE)
VALUES
	('LED'),
	('incandescent lamp');

INSERT INTO SHIP(SHIP_NAME, SHIP_TYPE)
VALUES
	('Titanic', 'passenger ship'),
	('black Pearl', 'Pirates ship'),
	('Gilda', 'vessel');

INSERT INTO LOCATION(SHIP_ID, FLASHLIGHT_ID)
VALUES
	(3, 1),
	(3, 2);	

INSERT INTO PORT (PORT_NAME, CITY_NAME)
VALUES
	('Sevkabel', 'Saint Petersburg'),
	('Samara river port', 'Samara');

INSERT INTO VISITOR_LIST (PERSON_ID, PORT_ID, TIME)
VALUES
	(2, 1, '2023-01-02 11:13:44+01'),
	(1, 2, '2023-02-02 11:13:44+01');
	
INSERT INTO SHIP_IN_PORT (PORT_ID, SHIP_ID, TIME)
VALUES
	(1, 2, '2023-03-02 11:13:44+01');

INSERT INTO WACHED_SHIP (PERSON_ID, SHIP_ID)
VALUES
	(1, 2),
	(2, 3);

INSERT INTO TIME (TIME_NAME, START_TIME, END_TIME)
VALUES
	('twilight', '16:38:00', '18:23:00'),
	('night', '18:23:00', '07:58:00');

INSERT INTO LIGHTS_ON_TIME(FLASHLIGHT_ID, TIME_NAME)
VALUES
	(1, 'twilight'),
	(2, 'night');
